const palette = {
  background: '#07111F',
  surface: '#111C2F',
  surfaceElevated: '#17243A',
  border: '#26344C',
  borderSoft: '#334761',
  textPrimary: '#F8FAFC',
  textSecondary: '#A7B4C7',
  textMuted: '#7E8CA3',
  primary: '#3B82F6',
  primaryLight: '#60A5FA',
  primarySoft: '#DBEAFE',
  danger: '#EF4444',
  success: '#22C55E',
  warning: '#F59E0B',
  info: '#38BDF8',
};

export const colors = {
  ...palette,
  cardBackground: palette.surface,
  cardBackgroundAlt: palette.surfaceElevated,
};

export const commonStyles = {
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  innerContainer: {
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 28,
  },
  logoIcon: {
    fontSize: 58,
    marginBottom: 14,
  },
  brandTitle: {
    fontSize: 26,
    fontWeight: '800',
    color: colors.textPrimary,
    letterSpacing: 1.2,
  },
  brandSubtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 4,
    textAlign: 'center',
  },
  formSection: {
    backgroundColor: colors.surface,
    padding: 22,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    elevation: 10,
  },
  inputLabel: {
    color: colors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
    marginBottom: 6,
    letterSpacing: 0.5,
  },
  inputField: {
    backgroundColor: colors.cardBackgroundAlt,
    color: colors.textPrimary,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderRadius: 14,
    fontSize: 15,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: colors.borderSoft,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 10,
    minHeight: 48,
    justifyContent: 'center',
    shadowColor: colors.primary,
    shadowOpacity: 0.28,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  linkText: {
    color: colors.textSecondary,
    fontSize: 14,
  },
  highlightText: {
    color: colors.primaryLight,
    fontWeight: '600',
  },
};
